"""empty message

Revision ID: 4be7c96e2b75
Revises: e1e808942960
Create Date: 2024-08-28 21:53:52.033092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be7c96e2b75'
down_revision = 'e1e808942960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('eventName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('eventDescription', sa.VARCHAR(length=200), nullable=True),
    sa.Column('eventStartDate', sa.INTEGER(), nullable=True),
    sa.Column('eventEndDate', sa.INTEGER(), nullable=True),
    sa.Column('eventLocation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('settingName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('settingValue', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tagName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tagDescription', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('formName', sa.VARCHAR(length=100), nullable=True),
    sa.Column('formDescription', sa.VARCHAR(length=200), nullable=True),
    sa.Column('formVersion', sa.VARCHAR(length=20), nullable=True),
    sa.Column('formFile', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
