"""empty message

Revision ID: 011b66b67027
Revises: 04e3a7cbfb88
Create Date: 2025-01-21 15:18:30.228559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011b66b67027'
down_revision = '04e3a7cbfb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_dl', sa.Boolean(), nullable=True))
        batch_op.drop_column('req_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_id', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('req_dl')

    # ### end Alembic commands ###
