"""empty message

Revision ID: 04e3a7cbfb88
Revises: 7f1b8c86e499
Create Date: 2025-01-21 15:15:24.788649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e3a7cbfb88'
down_revision = '7f1b8c86e499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_id', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('req_id')

    # ### end Alembic commands ###
