"""empty message

Revision ID: 053e6b9b67ef
Revises: d2ef509aedb9
Create Date: 2025-02-19 00:05:20.212334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053e6b9b67ef'
down_revision = 'd2ef509aedb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.drop_column('checked_in_at_local')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_at_local', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
