"""empty message

Revision ID: 0d70ad6f0262
Revises: 630468451dc7
Create Date: 2024-10-01 16:33:09.861429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d70ad6f0262'
down_revision = '630468451dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_addons',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('addon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_addons')
    # ### end Alembic commands ###
