"""empty message

Revision ID: 14e72800c7b9
Revises: ecd6634c0b99
Create Date: 2025-02-27 18:12:45.250964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e72800c7b9'
down_revision = 'ecd6634c0b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #with op.batch_alter_table('role', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'setting', ['setting_id'], ['id'])
	
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_column('setting_id')
        pass

    # ### end Alembic commands ###
