"""empty message

Revision ID: 1a7115b3ec71
Revises: 47ba2b371dfb
Create Date: 2025-02-05 22:32:07.949975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7115b3ec71'
down_revision = '47ba2b371dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###



    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True, default=0))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.drop_column('points')


    # ### end Alembic commands ###
