"""empty message

Revision ID: 1c69d19813a0
Revises: 37c5fa0d5fdf
Create Date: 2024-09-16 14:55:41.171776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c69d19813a0'
down_revision = '37c5fa0d5fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_qrcode_refresh', sa.Boolean(), nullable=True))
        batch_op.drop_column('lock_qrcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_qrcode', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('allow_qrcode_refresh')

    # ### end Alembic commands ###
