"""empty message

Revision ID: 2380093004fc
Revises: 49b41cd3acf0
Create Date: 2025-02-27 18:51:30.206174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2380093004fc'
down_revision = '49b41cd3acf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('setting', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('membership_role_id', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'role', ['membership_role_id'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('membership_role_id')

    # ### end Alembic commands ###
