"""empty message

Revision ID: 255407be2508
Revises: 2e7069cb7663
Create Date: 2024-09-16 13:58:23.714637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255407be2508'
down_revision = '2e7069cb7663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_qrcode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('lock_qrcode')

    # ### end Alembic commands ###
