"""empty message

Revision ID: 25684f9b291f
Revises: 3a9e6b951b97
Create Date: 2025-02-25 23:46:54.373611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25684f9b291f'
down_revision = '3a9e6b951b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_roles',
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_roles')
    # ### end Alembic commands ###
