"""empty message

Revision ID: 2e39c1b39416
Revises: 65268e344448
Create Date: 2024-09-13 23:45:19.927261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e39c1b39416'
down_revision = '65268e344448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_password_reset', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('allow_password_reset')

    # ### end Alembic commands ###
