"""empty message

Revision ID: 2e7069cb7663
Revises: ef11b4d740f9
Create Date: 2024-09-14 13:12:12.622454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7069cb7663'
down_revision = 'ef11b4d740f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_staff_on_checkin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_checkout_on_event_end', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('auto_checkout_on_event_end')
        batch_op.drop_column('notify_staff_on_checkin')

    # ### end Alembic commands ###
