"""empty message

Revision ID: 37c5fa0d5fdf
Revises: 255407be2508
Create Date: 2024-09-16 14:38:29.042619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c5fa0d5fdf'
down_revision = '255407be2508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_qrcode', sa.Boolean(), nullable=True))

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('lock_qrcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lock_qrcode', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('lock_qrcode')

    # ### end Alembic commands ###
