"""empty message

Revision ID: 3848e816a93b
Revises: 472a5441186d
Create Date: 2025-01-22 19:38:57.509749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3848e816a93b'
down_revision = '472a5441186d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint('uq_guest_email', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_guest_email', ['email'])

    # ### end Alembic commands ###
