"""empty message

Revision ID: 38a778d26f3f
Revises: 0030a036db01
Create Date: 2024-09-18 22:53:21.530364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a778d26f3f'
down_revision = '0030a036db01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_at_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at_time', sa.Time(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('checked_out_at_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('checked_out_at_time', sa.Time(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.drop_column('checked_out_at_time')
        batch_op.drop_column('checked_out_at_date')
        batch_op.drop_column('checked_out_at')
        batch_op.drop_column('checked_in_at_time')
        batch_op.drop_column('checked_in_at_date')

    # ### end Alembic commands ###
