"""empty message

Revision ID: 3a9e6b951b97
Revises: aa94742d4326
Create Date: 2025-02-25 23:44:41.430502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9e6b951b97'
down_revision = 'aa94742d4326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emailTemplate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailTemplate', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'email_template', ['emailTemplate'], ['id'])

    # ### end Alembic commands ###
