"""empty message

Revision ID: 454a8fc286fd
Revises: c1d5a52a9a41
Create Date: 2025-02-25 23:13:55.912812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454a8fc286fd'
down_revision = 'c1d5a52a9a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
       
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['role'], ['id'])

    op.drop_table('trigger_roles')
    # ### end Alembic commands ###
