"""empty message

Revision ID: 472a5441186d
Revises: 011b66b67027
Create Date: 2025-01-22 10:12:04.185426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472a5441186d'
down_revision = '011b66b67027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
