"""empty message

Revision ID: 47ba2b371dfb
Revises: c8e9f2ecbaba
Create Date: 2025-01-25 00:24:26.976296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ba2b371dfb'
down_revision = 'c8e9f2ecbaba'
branch_labels = None
depends_on = None

naming_convention = {
    "fk":
    "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog',naming_convention=naming_convention, schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_ID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('event_ID', 'event', ['event_ID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog',naming_convention=naming_convention, schema=None) as batch_op:
        batch_op.drop_constraint('event_ID', type_='foreignkey')
        batch_op.drop_column('event_ID')

    # ### end Alembic commands ###
