"""empty message

Revision ID: 48c0b9cf8610
Revises: 7147d2e17094
Create Date: 2024-10-11 11:07:01.381097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c0b9cf8610'
down_revision = '7147d2e17094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('eventID', sa.Integer(), nullable=True))
        batch_op.alter_column('checked_out_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('check_out_method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        #batch_op.create_foreign_key(None, 'event', ['eventID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('check_out_method',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('checked_out_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        #batch_op.drop_column('eventID')

    # ### end Alembic commands ###
