"""empty message

Revision ID: 49383fc2f8bf
Revises: 0d70ad6f0262
Create Date: 2024-10-03 21:01:28.893327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49383fc2f8bf'
down_revision = '0d70ad6f0262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paymentAmount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.drop_column('paymentAmount')

    # ### end Alembic commands ###
