"""empty message

Revision ID: 49b41cd3acf0
Revises: 14e72800c7b9
Create Date: 2025-02-27 18:36:55.612772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b41cd3acf0'
down_revision = '14e72800c7b9'
branch_labels = None
depends_on = None

naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(column_0_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    #with op.batch_alter_table('setting', schema=None, naming_convention=naming_convention) as batch_op:
        #batch_op.add_column(sa.Column('membership_role_id', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'role', ['membership_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('membership_role_id')

    # ### end Alembic commands ###
