"""empty message

Revision ID: 49f653195037
Revises: aa5628c2532c
Create Date: 2024-10-04 15:03:19.151881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f653195037'
down_revision = 'aa5628c2532c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
	    pass
        #batch_op.add_column(sa.Column('eventID', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'event', ['eventID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
	    pass
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_column('eventID')

    # ### end Alembic commands ###
