"""empty message

Revision ID: 4e0ee3f7fc87
Revises: 
Create Date: 2025-06-10 21:36:14.950445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0ee3f7fc87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('email_template',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('templateName', sa.String(length=100), nullable=True),
    # sa.Column('templateSubject', sa.String(length=100), nullable=True),
    # sa.Column('templateBody', sa.String(length=200), nullable=True),
    # sa.Column('templateEnabled', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_email_template'))
    # )
    # op.create_table('triggered_email_event',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=100), nullable=True),
    # sa.Column('timeDelta', sa.Integer(), nullable=True),
    # sa.Column('roleInitializeTriggered', sa.Boolean(), nullable=True),
    # sa.Column('eventVisitTriggered', sa.Boolean(), nullable=True),
    # sa.Column('eventMissedTriggered', sa.Boolean(), nullable=True),
    # sa.Column('paymentTriggered', sa.Boolean(), nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_triggered_email_event'))
    # )
    # op.create_table('email_log',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('emailSentAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    # sa.Column('emailTemplate', sa.Integer(), nullable=True),
    # sa.Column('emailRecipient', sa.String(length=100), nullable=True),
    # sa.Column('emailSubject', sa.String(length=100), nullable=True),
    # sa.Column('emailBody', sa.String(length=200), nullable=True),
    # sa.Column('emailSentBy', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['emailSentBy'], ['guest.id'], name=op.f('fk_email_log_emailSentBy_guest')),
    # sa.ForeignKeyConstraint(['emailTemplate'], ['email_template.id'], name=op.f('fk_email_log_emailTemplate_email_template')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_email_log'))
    # )
    # op.create_table('trigger_emailTemplates',
    # sa.Column('trigger_id', sa.Integer(), nullable=True),
    # sa.Column('emailTemplate_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['emailTemplate_id'], ['email_template.id'], name=op.f('fk_trigger_emailTemplates_emailTemplate_id_email_template')),
    # sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], name=op.f('fk_trigger_emailTemplates_trigger_id_triggered_email_event'))
    # )
    # op.create_table('trigger_events',
    # sa.Column('trigger_id', sa.Integer(), nullable=True),
    # sa.Column('event_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_trigger_events_event_id_event')),
    # sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], name=op.f('fk_trigger_events_trigger_id_triggered_email_event'))
    # )
    # op.create_table('trigger_roles',
    # sa.Column('trigger_id', sa.Integer(), nullable=True),
    # sa.Column('role_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_trigger_roles_role_id_role')),
    # sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], name=op.f('fk_trigger_roles_trigger_id_triggered_email_event'))
    # )
 

    # with op.batch_alter_table('event', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))

    # with op.batch_alter_table('guest', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('barStatus', sa.Integer(), nullable=True))
    #     batch_op.add_column(sa.Column('membershipEmailSent', sa.Boolean(), nullable=True))
    #     batch_op.add_column(sa.Column('membershipEmailSentDate', sa.DateTime(timezone=True), nullable=True))
    #     batch_op.add_column(sa.Column('membershipStart', sa.DateTime(timezone=True), nullable=True))
    #     batch_op.add_column(sa.Column('membershipEnd', sa.DateTime(timezone=True), nullable=True))
    #     batch_op.drop_constraint('uq_guest_email', type_='unique')

    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_ID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_guestlog_event_ID_event'), 'event', ['event_ID'], ['id'])
        batch_op.drop_column('checked_in_at_local')

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_dl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('points_per_credit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('show_bartip', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('membership_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_setting_membership_role_id_role'), 'role', ['membership_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_setting_membership_role_id_role'), type_='foreignkey')
        batch_op.drop_column('membership_role_id')
        batch_op.drop_column('show_bartip')
        batch_op.drop_column('points_per_credit')
        batch_op.drop_column('req_dl')

    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_at_local', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_guestlog_event_ID_event'), type_='foreignkey')
        batch_op.drop_column('event_ID')

    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.drop_column('points')

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_guest_email', ['email'])
        batch_op.drop_column('membershipEnd')
        batch_op.drop_column('membershipStart')
        batch_op.drop_column('membershipEmailSentDate')
        batch_op.drop_column('membershipEmailSent')
        batch_op.drop_column('barStatus')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.drop_column('pointChange')

    op.drop_table('trigger_roles')
    op.drop_table('trigger_events')
    op.drop_table('trigger_emailTemplates')
    op.drop_table('email_log')
    op.drop_table('triggered_email_event')
    op.drop_table('email_template')
    # ### end Alembic commands ###
