"""empty message

Revision ID: 65268e344448
Revises: 6adad59342ea
Create Date: 2024-09-13 21:56:52.099173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65268e344448'
down_revision = '6adad59342ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.alter_column('paymentMethod',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.alter_column('paymentMethod',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
