"""empty message

Revision ID: 6adad59342ea
Revises: 
Create Date: 2024-09-13 21:45:30.787122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adad59342ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eventName', sa.String(length=100), nullable=True),
    sa.Column('eventDescription', sa.String(length=200), nullable=True),
    sa.Column('eventStartDate', sa.Integer(), nullable=True),
    sa.Column('eventEndDate', sa.Integer(), nullable=True),
    sa.Column('eventLocation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('fetUsername', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('termsCheck', sa.Boolean(), nullable=True),
    sa.Column('termsDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastVisit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastCheckOut', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('permissions', sa.String(length=200), nullable=True),
    sa.Column('skip_payment_at_checkin', sa.Boolean(), nullable=True),
    sa.Column('skip_tos_update_at_checkin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tos', sa.String(), nullable=True),
    sa.Column('tos_updated', sa.String(length=100), nullable=True),
    sa.Column('checkInCooldownSeconds', sa.Integer(), nullable=True),
    sa.Column('checkOutBasedOnTime', sa.Boolean(), nullable=True),
    sa.Column('checkOutTime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkOutBasedOnEventEndTime', sa.Boolean(), nullable=True),
    sa.Column('show_cashapp', sa.Boolean(), nullable=True),
    sa.Column('show_paypal', sa.Boolean(), nullable=True),
    sa.Column('show_venmo', sa.Boolean(), nullable=True),
    sa.Column('show_cash', sa.Boolean(), nullable=True),
    sa.Column('show_credit', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagName', sa.String(length=100), nullable=True),
    sa.Column('tagDescription', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_transaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('guest', sa.Integer(), nullable=False),
    sa.Column('authorizedSource', sa.String(length=100), nullable=False),
    sa.Column('authorizedBy', sa.Integer(), nullable=True),
    sa.Column('generalAmountChange', sa.Integer(), nullable=False),
    sa.Column('specialEventAmountChange', sa.Integer(), nullable=False),
    sa.Column('privateSessionAmountChange', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['authorizedBy'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['guest'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastUpdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('generalAmount', sa.Integer(), nullable=False),
    sa.Column('specialEventAmount', sa.Integer(), nullable=False),
    sa.Column('privateSessionAmount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_roles',
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('guestlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('paymentMethod', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guestlog')
    op.drop_table('guest_roles')
    op.drop_table('guest_credit')
    op.drop_table('credit_transaction_log')
    op.drop_table('tag')
    op.drop_table('setting')
    op.drop_table('role')
    op.drop_table('guest')
    op.drop_table('event')
    # ### end Alembic commands ###
