"""empty message

Revision ID: 70d5cf6e2cff
Revises: 25684f9b291f
Create Date: 2025-02-25 23:50:31.690081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d5cf6e2cff'
down_revision = '25684f9b291f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_emailTemplates',
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('emailTemplate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emailTemplate_id'], ['email_template.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], )
    )
    op.create_table('trigger_events',
    sa.Column('trigger_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggered_email_event.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trigger_events')
    op.drop_table('trigger_emailTemplates')
    # ### end Alembic commands ###
