"""empty message

Revision ID: 7147d2e17094
Revises: a5a9e5f5f245
Create Date: 2024-10-04 15:27:03.058947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7147d2e17094'
down_revision = 'a5a9e5f5f245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_guest_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_guest_uuid'), ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_guest_uuid'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_guest_email'), type_='unique')

    # ### end Alembic commands ###
