"""empty message

Revision ID: 7f1b8c86e499
Revises: 25785bd131d7
Create Date: 2024-12-14 11:44:27.829733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1b8c86e499'
down_revision = '25785bd131d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkedIn', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('checkedIn')

    # ### end Alembic commands ###
