"""empty message

Revision ID: 90e03ac1c01c
Revises: 1a7115b3ec71
Create Date: 2025-02-05 22:40:22.887443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e03ac1c01c'
down_revision = '1a7115b3ec71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointChange', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.drop_column('pointChange')

    # ### end Alembic commands ###
