"""empty message

Revision ID: 92b2809d9494
Revises: 74fd574c2f03
Create Date: 2024-09-20 22:31:02.427657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b2809d9494'
down_revision = '74fd574c2f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkin_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('checkin_blocked')

    # ### end Alembic commands ###
