"""empty message

Revision ID: 9b9dbb7c6599
Revises: caa53a4446fe
Create Date: 2025-06-14 18:58:10.740661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9dbb7c6599'
down_revision = 'caa53a4446fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_file'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_file')
    # ### end Alembic commands ###
