"""empty message

Revision ID: 9d703031abf5
Revises: 4e0ee3f7fc87
Create Date: 2025-06-10 21:49:17.934789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d703031abf5'
down_revision = '4e0ee3f7fc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('_alembic_tmp_guest')
    # with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
    #     batch_op.alter_column('pointChange',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barStatus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('membershipEmailSent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('membershipEmailSentDate', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('membershipStart', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('membershipEnd', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint('uq_guest_email', type_='unique')

    # with op.batch_alter_table('guest_credit', schema=None) as batch_op:
    #     batch_op.alter_column('points',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_guest_email', ['email'])
        batch_op.drop_column('membershipEnd')
        batch_op.drop_column('membershipStart')
        batch_op.drop_column('membershipEmailSentDate')
        batch_op.drop_column('membershipEmailSent')
        batch_op.drop_column('barStatus')

    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.alter_column('pointChange',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_guest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(), nullable=True),
    sa.Column('fetUsername', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('termsCheck', sa.BOOLEAN(), nullable=True),
    sa.Column('termsDate', sa.DATETIME(), nullable=True),
    sa.Column('lastVisit', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('lastCheckOut', sa.DATETIME(), nullable=True),
    sa.Column('allow_qrcode_refresh', sa.BOOLEAN(), nullable=True),
    sa.Column('checkin_blocked', sa.BOOLEAN(), nullable=True),
    sa.Column('checkedIn', sa.BOOLEAN(), nullable=True),
    sa.Column('barStatus', sa.INTEGER(), nullable=True),
    sa.Column('membershipEmailSent', sa.BOOLEAN(), nullable=True),
    sa.Column('membershipEmailSentDate', sa.DATETIME(), nullable=True),
    sa.Column('membershipStart', sa.DATETIME(), nullable=True),
    sa.Column('membershipEnd', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uq_guest_uuid')
    )
    # ### end Alembic commands ###
