"""empty message

Revision ID: a5e2e90670ae
Revises: c479560f0f6b
Create Date: 2025-02-25 23:20:35.403808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e2e90670ae'
down_revision = 'c479560f0f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        #batch_op.create_foreign_key(None, 'role', ['role'], ['id'])

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
