"""empty message

Revision ID: a9e263e9edf7
Revises: ded0bd907028
Create Date: 2025-02-27 19:32:44.046442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e263e9edf7'
down_revision = 'ded0bd907028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membershipEmailSent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('membershipEmailSentDate', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('membershipStart', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('membershipEnd', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('membershipEnd')
        batch_op.drop_column('membershipStart')
        batch_op.drop_column('membershipEmailSentDate')
        batch_op.drop_column('membershipEmailSent')

    # ### end Alembic commands ###
