"""empty message

Revision ID: aa5628c2532c
Revises: 49383fc2f8bf
Create Date: 2024-10-03 22:56:25.079932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5628c2532c'
down_revision = '49383fc2f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('checked_in_at_local', sa.DateTime(timezone=True), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.drop_column('checked_in_at_local')
        pass

    # ### end Alembic commands ###
