"""empty message

Revision ID: aa94742d4326
Revises: 3bbbc606253b
Create Date: 2025-02-25 23:42:39.608724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa94742d4326'
down_revision = '3bbbc606253b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'event', ['event'], ['id'])

    # ### end Alembic commands ###
