"""empty message

Revision ID: b160388d909b
Revises: 9b9dbb7c6599
Create Date: 2025-06-14 21:01:25.657853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b160388d909b'
down_revision = '9b9dbb7c6599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['menu_file.id'], name=op.f('fk_menu_item_image_id_menu_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item')
    # ### end Alembic commands ###
