"""empty message

Revision ID: c1d5a52a9a41
Revises: 053e6b9b67ef
Create Date: 2025-02-25 22:56:35.853498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d5a52a9a41'
down_revision = '053e6b9b67ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('templateName', sa.String(length=100), nullable=True),
    sa.Column('templateSubject', sa.String(length=100), nullable=True),
    sa.Column('templateBody', sa.String(length=200), nullable=True),
    sa.Column('templateEnabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emailSentAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('emailTemplate', sa.Integer(), nullable=True),
    sa.Column('emailRecipient', sa.String(length=100), nullable=True),
    sa.Column('emailSubject', sa.String(length=100), nullable=True),
    sa.Column('emailBody', sa.String(length=200), nullable=True),
    sa.Column('emailSentBy', sa.Integer(), nullable=True),
    sa.Column('emailSentTo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['emailSentBy'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['emailSentTo'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['emailTemplate'], ['email_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('triggered_email_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('timeDelta', sa.Integer(), nullable=True),
    sa.Column('emailTemplate', sa.Integer(), nullable=True),
    sa.Column('roleInitializeTriggered', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('eventVisitTriggered', sa.Boolean(), nullable=True),
    sa.Column('eventMissedTriggered', sa.Boolean(), nullable=True),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('paymentTriggered', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emailTemplate'], ['email_template.id'], ),
    sa.ForeignKeyConstraint(['event'], ['event.id'], ),
    sa.ForeignKeyConstraint(['role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('triggered_email_event')
    op.drop_table('email_log')
    op.drop_table('email_template')
    # ### end Alembic commands ###
