"""empty message

Revision ID: c8e9f2ecbaba
Revises: c8b388953d5f
Create Date: 2025-01-24 23:50:29.020706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8e9f2ecbaba'
down_revision = 'c8b388953d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('eventID', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'event', ['eventID'], ['id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_column('eventID')
        pass

    # ### end Alembic commands ###
