"""empty message

Revision ID: caa53a4446fe
Revises: 9d703031abf5
Create Date: 2025-06-10 21:50:58.002722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa53a4446fe'
down_revision = '9d703031abf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_credit_transaction_log')
    # with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
    #     batch_op.alter_column('pointChange',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # with op.batch_alter_table('guest_credit', schema=None) as batch_op:
    #     batch_op.alter_column('points',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.alter_column('pointChange',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_credit_transaction_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('guest', sa.INTEGER(), nullable=False),
    sa.Column('authorizedSource', sa.VARCHAR(length=100), nullable=False),
    sa.Column('authorizedBy', sa.INTEGER(), nullable=True),
    sa.Column('generalAmountChange', sa.INTEGER(), nullable=False),
    sa.Column('specialEventAmountChange', sa.INTEGER(), nullable=False),
    sa.Column('privateSessionAmountChange', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('pointChange', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['authorizedBy'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['guest'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
