"""empty message

Revision ID: d09e9aab1b86
Revises: ff2ca5774f32
Create Date: 2025-02-25 23:40:45.714927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09e9aab1b86'
down_revision = 'ff2ca5774f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        pass
        #batch_op.create_foreign_key(None, 'role', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
