"""empty message

Revision ID: d2ef509aedb9
Revises: 90e03ac1c01c
Create Date: 2025-02-05 23:17:55.970151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ef509aedb9'
down_revision = '90e03ac1c01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.alter_column('pointChange',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_per_credit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('points_per_credit')

    with op.batch_alter_table('guest_credit', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('credit_transaction_log', schema=None) as batch_op:
        batch_op.alter_column('pointChange',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
