"""empty message

Revision ID: ded0bd907028
Revises: 2380093004fc
Create Date: 2025-02-27 18:53:25.905629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded0bd907028'
down_revision = '2380093004fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'role', ['membership_role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('membership_role_id')

    # ### end Alembic commands ###
