"""empty message

Revision ID: e1e808942960
Revises: 
Create Date: 2024-08-27 22:31:18.546084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e808942960'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eventDate', sa.DATETIME(), nullable=True))
        batch_op.drop_column('eventEndDate')
        batch_op.drop_column('eventStartDate')

    # ### end Alembic commands ###
