"""empty message

Revision ID: e5dccfac1c2c
Revises: 38a778d26f3f
Create Date: 2024-09-18 23:23:29.628573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dccfac1c2c'
down_revision = '38a778d26f3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_out_method', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.drop_column('check_out_method')

    # ### end Alembic commands ###
