"""empty message

Revision ID: ef11b4d740f9
Revises: 2e39c1b39416
Create Date: 2024-09-14 11:27:31.707371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef11b4d740f9'
down_revision = '2e39c1b39416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_login_to_backoffice', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('allow_login_to_backoffice')

    # ### end Alembic commands ###
