"""empty message

Revision ID: f28b49980bed
Revises: 48c0b9cf8610
Create Date: 2024-10-11 11:08:08.748215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28b49980bed'
down_revision = '48c0b9cf8610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('eventID', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'event', ['eventID'], ['id'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        #batch_op.drop_column('eventID')
        pass

    # ### end Alembic commands ###
