"""empty message

Revision ID: fbabdda34532
Revises: 1bcfde2a3c8c
Create Date: 2024-08-29 22:21:49.699747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbabdda34532'
down_revision = '1bcfde2a3c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestlog', schema=None) as batch_op:
        batch_op.drop_column('checked_in_at')

    # ### end Alembic commands ###
