"""empty message

Revision ID: ff2ca5774f32
Revises: d05fb521fd14
Create Date: 2025-02-25 23:34:04.102933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2ca5774f32'
down_revision = 'd05fb521fd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        #batch_op.create_foreign_key(None, 'role', ['role'], ['id'])
	    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('triggered_email_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
